// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	account "github.com/mastanca/accounting-notebook-be/internal/domain/account"

	mock "github.com/stretchr/testify/mock"
)

// GetAccount is an autogenerated mock type for the GetAccount type
type GetAccount struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *GetAccount) Execute(ctx context.Context) (*account.Account, error) {
	ret := _m.Called(ctx)

	var r0 *account.Account
	if rf, ok := ret.Get(0).(func(context.Context) *account.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
