// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// PingHandler is an autogenerated mock type for the PingHandler type
type PingHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: c
func (_m *PingHandler) Handle(c *gin.Context) {
	_m.Called(c)
}
